# Generated by Django 5.2.1 on 2025-06-24 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DDSproject', '0002_alumno_docente_tema_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='docente',
            name='costo_semanal',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='curso',
            name='docente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DDSproject.docente'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='tema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DDSproject.tema'),
        ),
    ]
